### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by kgryte** [compute-io/filled#1]
The current name follows numpy's [full](http://docs.scipy.org/doc/numpy/reference/generated/numpy.full.html). In contrast, Matlab's [full](http://www.mathworks.com/help/matlab/ref/full.html) is used to convert from a sparse to a dense matrix.

I worry that the numpy convention may lead to confusion with `full` rank. And Matlab's convention is a bit odd: why not name the function `dense`?

To my knowledge, `R` does not have an explicit function for this operation. It seems one can provide a value to `matrix(val,m,n)`. In Matlab, to have every value be the same `val .* ones(m,n)`.

`repeat` is too general, as in we may want to reserve the name for something else. `fill` is already used. `dense` is possible, but may want to reserve that name for something which more explicitly refers to storage. Others?

Maybe `filled`?

**Comment by Planeshifter** [comment]
Hmm, why is `fill` not an option? We certainly do not have such a module yet. And in ES6, arrays have a `fill` method which performs the same operation as this module.

**Comment by Planeshifter** [comment]
I assume that we would like to have another `fill` module to set the values of an _existing_ `array` or `matrix`. In that case, `filled` sounds good to me.

**Comment by kgryte** [comment]
Re: `fill`. Such a module is on the roadmap. 

Re: ES6. [`Array#fill`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill) and [`TypedArray#fill`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/fill) are a bit different, in that they work on existing `arrays`. This module should be considered the generalization of `zeros` and `ones`.

Re: `filled`. Yeah, I feel like this name makes the most semantic sense.

Thanks for your input!
